name: ssh-into-aws-ec2

on: 
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
        run: |
          touch private_key.pem
          echo "1"
          echo "$SSH_PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          echo "2"
          ssh -i "private_key.pem" ec2-user@ec2-54-179-190-54.ap-southeast-1.compute.amazonaws.com
          echo "3"
          ls
