name: ssh-into-aws-ec2

on: 
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-179-190-54.ap-southeast-1.compute.amazonaws.com
          username: ec2-user
          key: ${ { secrets.EC2_SSH_KEY }}
      - name: Checkout the files
        run: ls -l
